### ISSUE TITLE
Docker Build Fails: Environment Variable Not Available During Build Stage

### ISSUE THREAD

**Issue by MAVRICK-1** [kubestellar/ui#912]
# Docker Build Fails: Environment Variable Not Available During Build Stage

## Description
The Docker build process is failing because the `VITE_BASE_URL` environment variable is undefined during the build stage. The `vite-plugin-environment` plugin throws an error when it cannot find the required environment variable.

## Error Message
```
error during build:
Error: vite-plugin-environment: the `VITE_BASE_URL` environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://github.com/ElMassimo/vite-plugin-environment for guidance.
```

## Root Cause
Environment variables defined in `docker-compose.yml` under the `environment` section are only available at container runtime, not during the Docker build process. The `npm run build` command runs during the build stage and requires access to these environment variables.

## Current Configuration
**Dockerfile:**
```dockerfile
# Environment variables set here are not available during build
ENV VITE_APP_VERSION=0.1.0
ENV VITE_SKIP_PREREQUISITES_CHECK=true
# Build frontend - fails here because VITE_BASE_URL is missing
RUN npm run build
```

**docker-compose.yml:**
```yaml
services:
  frontend:
    environment:
      - VITE_BASE_URL=http://localhost:4000  # Only available at runtime
```

## Proposed Solution
Use Docker build arguments to pass environment variables during the build stage:

**Updated Dockerfile:**
```dockerfile
# Accept build arguments
ARG VITE_APP_VERSION=0.1.0
ARG VITE_SKIP_PREREQUISITES_CHECK=true
ARG VITE_BASE_URL

# Set environment variables from build args
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_SKIP_PREREQUISITES_CHECK=$VITE_SKIP_PREREQUISITES_CHECK
ENV VITE_BASE_URL=$VITE_BASE_URL

# Build frontend
RUN npm run build
```

**Updated docker-compose.yml:**
```yaml
services:
  frontend:
    build:
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=http://localhost:4000
        - VITE_SKIP_PREREQUISITES_CHECK=true
        - VITE_APP_VERSION=0.1.0
```

## Alternative Solutions
1. **Set default values in vite config:**
   ```typescript
   EnvironmentPlugin({
     VITE_BASE_URL: 'http://localhost:4000',
     VITE_SKIP_PREREQUISITES_CHECK: 'true'
   })
   ```

2. **Use .env file with default values**

## Steps to Reproduce
1. Run `docker-compose build`
2. Observe the build failure during the `npm run build` step

## Environment
- Docker version: [version]
- Docker Compose version: [version]
- Node.js version: 18
- Build tool: Vite

## Expected Behavior
The Docker build should complete successfully with all required environment variables available during the build process.

## Acceptance Criteria
- [ ] Docker build completes without errors
- [ ] Frontend container starts successfully
- [ ] Environment variables are properly injected during build
- [ ] Application loads correctly with proper configuration
